from adam.language.dependency.universal_dependencies import NOUN, ADJECTIVE
from adam.language.lexicon import LexiconEntry
from adam.language.ontology_dictionary import OntologyLexicon
from adam.ontology.phase1_ontology import (
    PAPER,
    RED,
    BLUE,
    GREEN,
    BLACK,
    WHITE,
    BROWN,
    PURPLE,
    YELLOW,
    ORANGE_COLOR,
)
from adam.ontology.phase3_ontology import (
    GAILA_PHASE_3_ONTOLOGY,
    APPLE,
    ORANGE,
    BANANA,
    BALL,
    BOOK,
    TABLE,
    CHAIR,
    SOFA,
    BOX,
    FLOOR,
    WINDOW,
    CUP,
    DESK,
    TOY_TRUCK,
    TOY_SEDAN,
    BLOCK,
    TRIANGULAR,
    SPHERICAL,
    CUBIC,
    PLASTIC,
    WOOD,
    PYRAMID_BLOCK,
    SPHERICAL_BLOCK,
    CUBE_BLOCK,
    MUG,
)

GAILA_PHASE_3_ENGLISH_LEXICON = OntologyLexicon(
    ontology=GAILA_PHASE_3_ONTOLOGY,
    ontology_node_to_word=(
        (APPLE, LexiconEntry("apple", NOUN, plural_form="apples")),
        (ORANGE, LexiconEntry("orange", NOUN, plural_form="oranges")),
        (BANANA, LexiconEntry("banana", NOUN, plural_form="bananas")),
        (BALL, LexiconEntry("ball", NOUN, plural_form="balls")),
        (BOOK, LexiconEntry("book", NOUN, plural_form="books")),
        (TABLE, LexiconEntry("table", NOUN, plural_form="tables")),
        (CHAIR, LexiconEntry("chair", NOUN, plural_form="chairs")),
        (SOFA, LexiconEntry("sofa", NOUN, plural_form="sofas")),
        (BLOCK, LexiconEntry("block", NOUN, plural_form="blocks")),
        (PYRAMID_BLOCK, LexiconEntry("pyramid", NOUN, plural_form="pyramids")),
        (SPHERICAL_BLOCK, LexiconEntry("sphere", NOUN, plural_form="spheres")),
        (CUBE_BLOCK, LexiconEntry("cube", NOUN, plural_form="cubes")),
        (BOX, LexiconEntry("box", NOUN, plural_form="boxes")),
        (FLOOR, LexiconEntry("floor", NOUN, plural_form="floors")),
        (WINDOW, LexiconEntry("window", NOUN, plural_form="windows")),
        (CUP, LexiconEntry("cup", NOUN, plural_form="cups")),
        (MUG, LexiconEntry("mug", NOUN, plural_form="mugs")),
        (PAPER, LexiconEntry("paper", NOUN, plural_form="papers")),
        (DESK, LexiconEntry("desk", NOUN, plural_form="desks")),
        (TOY_TRUCK, LexiconEntry("truck", NOUN, plural_form="trucks")),
        (TOY_SEDAN, LexiconEntry("car", NOUN, plural_form="cars")),
        (TRIANGULAR, LexiconEntry("triangular", ADJECTIVE)),
        (SPHERICAL, LexiconEntry("spherical", ADJECTIVE)),
        (CUBIC, LexiconEntry("cubic", ADJECTIVE)),
        (RED, LexiconEntry("red", ADJECTIVE)),
        (BLUE, LexiconEntry("blue", ADJECTIVE)),
        (GREEN, LexiconEntry("green", ADJECTIVE)),
        (BLACK, LexiconEntry("black", ADJECTIVE)),
        (WHITE, LexiconEntry("white", ADJECTIVE)),
        (BROWN, LexiconEntry("brown", ADJECTIVE)),
        (PURPLE, LexiconEntry("purple", ADJECTIVE)),
        (YELLOW, LexiconEntry("yellow", ADJECTIVE)),
        (ORANGE_COLOR, LexiconEntry("orange", ADJECTIVE)),
        (PLASTIC, LexiconEntry("plastic", ADJECTIVE)),
        (WOOD, LexiconEntry("wood", ADJECTIVE)),
    ),
)
